### ISSUE TITLE
貌似sh没有，请帮助

### ISSUE THREAD

**Issue by hu9msbedu** [jiwenxing/qiniu-image-tool#12]
`/Users/j.applesid/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/FAECC616-DE24-42E5-BD30-A73ECDABCFB5:2424:2455: execution error: sh: /usr/local/bin/qshell: No such file or directory (127)`

**Comment by jiwenxing** [comment]
从[七牛官网](https://developer.qiniu.com/kodo/tools/1302/qshell)下载，下载后把名字改为`qshell`，放在`/usr/local/bin/`这个目录即可

**Comment by hu9msbedu** [comment]
感谢 现在提示：
`No file or image data found on the clipboard.`

**Comment by hu9msbedu** [comment]
截图复制过了。command +shift +4 然后在用hot快捷键。

**Comment by jiwenxing** [comment]
cmd+option+c 可以看到剪贴板内容，看看上传之前剪贴板是不是截图数据，可以找一张本地的照片也试一下本地上传

**Comment by hu9msbedu** [comment]
cmd+option+c  看到是空的，实际可以复制粘贴图片。
不过选中图片可以上传，可以得到求牛的地址链接，可实际没有传到七牛，得到的图片url打不开。

**Comment by hu9msbedu** [comment]
问题解决。截图有空格的问题，
