### ISSUE TITLE
剪贴板有图片的情况下，按下热键报错，请问该怎么解决。

### ISSUE THREAD

**Issue by DogJun** [jiwenxing/qiniu-image-tool#15]
[2019-01-30 10:39:22][ERROR: action.script] *** Error creating a JP2 color space: falling back to sRGB
*** Error creating a JP2 color space: falling back to sRGB
/Users/huangwenjun/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/6DE62051-2A67-4E0F-B1DD-DDA7FA44B741:2331:2362: execution error: Error: command account receives zero or three args, received 2

**Comment by DogJun** [comment]
问题已经解决，新版本qshell需要这样添加账号信息：qshell account AccessKey SecretKey Name

**Comment by F12EN** [comment]
![image](https://user-images.githubusercontent.com/25075086/60694055-57ed3500-9f0f-11e9-9ac8-5cd1350b6b5a.png)
我的也是用新版qshell，除了在qshell添加账号信息之外，还需要红框线中这两句命令用“-- ”注释掉，才可以上传。
