### ISSUE TITLE
mac下张贴出的地址有重复

### ISSUE THREAD

**Issue by MuYunyun** [jiwenxing/qiniu-image-tool#2]
原来应该是
![](http://oqhtscus0.bkt.clouddn.com/
oqhtscus0.bkt.clouddn.com/c9f65375830453cec88688f3d9149306.png)

command+option+v后出来的是：
![](http://oqhtscus0.bkt.clouddn.com
http://oqhtscus0.bkt.clouddn.com/
oqhtscus0.bkt.clouddn.com/c9f65375830453cec88688f3d9149306.png)

**Comment by MuYunyun** [comment]
此外能否给图片进行自动压缩呢~

**Comment by jiwenxing** [comment]
1. 第一次使用快捷键 command+option+v 的时候会执行上传操作并将返回的url放到剪切板和输出到当前编辑器，如果要再次使用相同的链接直接 command+v 进行常规的粘贴即可。
2. 做压缩的话可能需要引入更多的第三方插件，会增加使用复杂性，1.0版本我希望能够最快最方便的用起来，2.0版本会考虑加入图片压缩功能。

**Comment by MuYunyun** [comment]
可能是我描述的不清楚，我遇到的bug是返回的url里七牛云的http地址出现了两次，它返回如下形式：
![](**http://oqhtscus0.bkt.clouddn.comhttp://oqhtscus0.bkt.clouddn.com/**
oqhtscus0.bkt.clouddn.com/c9f65375830453cec88688f3d9149306.png)

**Comment by jiwenxing** [comment]
哦，那你这个问题比较奇怪，你把你环境变量里配的bucketDomain截个图，然后在Alfred中双击workflow里的`run script`将其中的脚本代码粘贴到下面我看一眼，再描述一下你的操作步骤，另外你这个问题是上传本地图片和截图都会遇到吗？

**Comment by MuYunyun** [comment]
环境变量：
![image](https://cloud.githubusercontent.com/assets/19354791/26461346/7adec174-41af-11e7-8346-f55b92391a68.png)
脚本代码
`-- config start
property bucket : (system attribute "bucket")
property bucketDomain : (system attribute "bucketDomain")
property AccessKey : (system attribute "AccessKey")
property SecretKey : (system attribute "SecretKey")
-- config end

-- md5(date) as file name
set fileName to do shell script "date \"+%Y%m%d%H%M%S\" | md5"

-- see if clipboard is a file
set filePath to ""
try
	set clipPath to the clipboard as «class furl»
	set filePath to clipPath as alias
	-- like "/Users/jverson/Pictures/igarss/IMG_20140720_221838.jpg"
	set filePath to quoted form of POSIX path of filePath
	set filePath to second item of my theSplit(filePath, "'")
	set tempArray to my theSplit(filePath, ".")
	-- like "jpg" or "png" or "gif" or "mp4"
	set fileType to last item of tempArray
end try

if filePath is not "" then
	set fileName to fileName & "." & fileType
	set markdownUrl to my upload(fileName, filePath, fileType)
	return markdownUrl --end
end if


-- see if clipboard is image data
set jpegDATA to ""
try
	set jpegDATA to the clipboard as JPEG picture
end try
if jpegDATA is not "" then
	set tempPath to "/tmp/"
	set fileName to fileName & ".jpg"
	set filePath to tempPath & fileName
	set theFile to open for access filePath with write permission
	write jpegDATA to theFile
	close access theFile
	set markdownUrl to my upload(fileName, filePath, "jpg")
    -- delete temp file
    do shell script "rm " & filePath
	return markdownUrl
end if

beep 1
display dialog ¬
	"No file or image data found on the clipboard." with icon ¬
	note buttons {"Whatever"} default button 1
return

-- string split function
-- ref: http://erikslab.com/2007/08/31/applescript-how-to-split-a-string/
on theSplit(theString, theDelimiter)
	-- save delimiters to restore old settings
	set oldDelimiters to AppleScript's text item delimiters
	-- set delimiters to delimiter to be used
	set AppleScript's text item delimiters to theDelimiter
	-- create the array
	set theArray to every text item of theString
	-- restore the old setting
	set AppleScript's text item delimiters to oldDelimiters
	-- return the result
	return theArray
end theSplit

-- upload image to qiniu
on upload(fileName, filePath, fileType)
    -- compress image todo..

    -- qiniu account set
    set account_commond to "/usr/local/bin/qshell account " & AccessKey & " " & SecretKey
    do shell script account_commond
    -- upload to qiniu
	set upload_command to "/usr/local/bin/qshell fput " & bucket & " " & fileName & " " & filePath
	do shell script upload_command
    -- strcat url
    set resourceUrl to bucketDomain & fileName
    if (fileType is "png") or (fileType is "jpg") or (fileType is "gif") or (fileType is "bmp") or (fileType is "jpeg") then
	    set markdownUrl to "![](" & resourceUrl & ")"
	    return markdownUrl
    else
        return resourceUrl
    end if

end upload

-- ref:https://discussions.apple.com/thread/2379870?start=0&tstart=0`

操作步骤：
用截图软件截图后，或者本地文件选择copy，然后直接按设置好的command+option+v，然后在图片成功上传到七牛云图床上，剪贴板上也有相应的连接，只是http://oqhtscus0.bkt.clouddn.com重复了2遍

上传本地图片和截图都会遇到

**Comment by jiwenxing** [comment]
代码看不出任何会导致该现象的问题，你环境变量配置的bucketDomain后面少一个“／”，但不是导致这个问题的原因，可以加我qq412516590，有空咱们一起排查一下

**Comment by fakeyanss** [comment]
我有相同的问题

**Comment by MuYunyun** [comment]
@fakeYanss 有解决么
