### ISSUE TITLE
qshell account最新版本参数

### ISSUE THREAD

**Issue by zhuxingsheng** [jiwenxing/qiniu-image-tool#24]
qshell account [--overwrite | -w]<Your AccessKey> <Your SecretKey> <Your Account Name>
增加了一个参数，qimage-mac只有两个参数

set account_commond to "/usr/local/bin/qshell account " & AccessKey & " " & SecretKey

**Comment by zyyoo** [comment]
你删除掉这行和下面一行,去shell执行下/usr/local/bin/qshell account 'ak' 'sk' '随意一个名字' 就可以正常使用了
