### ISSUE TITLE
能否使上传的图片名称一致

### ISSUE THREAD

**Issue by osen77** [jiwenxing/qiniu-image-tool#4]
Hi，我有个问题困扰我，当我上传一张命名好的图片时，返回的是混乱的图片名称，能否使名称一致呢?

**Comment by jiwenxing** [comment]
这个是防止同名图片上传时会发生覆盖造成图片丢失，不过你可以自己在脚本中修改文件名的生成策略，目前是“当前时间+三位随机数”

**Comment by hscspring** [comment]
能改成自己命名就好了。

**Comment by jiwenxing** [comment]
最新的提交提供了一个额外的workflow：`Qiniu - support user-defined file name.alfredworkflow`，有以下特点：
1. 上传本地图片则默认使用原图片名称
2. 上传截图或网络图片时，会弹窗提示输入自定义图片名称

这样应该可以解决你们的问题

**Comment by hscspring** [comment]
厉害了~~~  
我还吭哧吭哧自己改了半天，不过没有你的效果好~  
谢谢 O(∩_∩)O
